name: Build and Publish Docker Image

on:
  push:
    branches:
      - main 
      - develop
      - feature/* 
      - bugfix/*  
      - release/* 
      - hotfix/*  
      - support/*  
    tags:        
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write 
    steps:
      - name: ⬇️  Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 🥂 Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: ./src/global.json 

      
      - name: 🔢  GitVersion install
        uses: gittools/actions/gitversion/setup@v3.2.0
        with:
          versionSpec: '6.1.x'
          preferLatestVersion: true
      
      - name: 🔢  Gitversion - Determine version
        id: version
        uses: gittools/actions/gitversion/execute@v3.2.0
        with:
          useConfigFile: true
          configFilePath: ${{ github.workspace }}/build/GitVersion.yaml
          updateProjectFiles: true
          
      - name: 👤  Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🚀 Publish
        run: |
          BASE=ghcr.io/${{ github.repository_owner }}/jdc-build-dependencygraph
          TAG=${BASE}:${{ steps.version.outputs.semver }}
          docker build -t ${TAG} -f ./build/Dockerfile . --secret id=GITHUB_TOKEN,env=GITHUB_TOKEN
          if [ "${{ github.ref_name }}" == "main" ]; then
            LATEST_TAG=${BASE}:latest
            docker image tag ${TAG} ${LATEST_TAG}
          fi
          docker image push ${BASE} --all-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: docker logout
        run: docker logout ghcr.io
